spring:
  profile:
    active: local
  h2:
    console:
      enabled: true
      path: /h2-console
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  redis:
#    host: localhost
#    port: 6379

logging.level:
  org.hibernate.SQL: debug

