cloud:
  aws:
    credentials:
      accessKey: AKIAVBY3F3M57OG4IXNA
      secretKey: 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
    s3:
      bucket: moamoa1-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
