spring:
  profiles:
    active: local
    include: oauth
  datasource:
    url: jdbc:mysql://localhost:3306/moamoa?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  redis:
#    host: localhost
#    port: 6379

logging.level:
  org.hibernate.SQL: debug

