spring:
  profiles:
    active: local
    include:
      - oauth
      - aws
  datasource:
    url: jdbc:mysql://moamoa1.cuax43rzes2d.ap-northeast-2.rds.amazonaws.com:3306/moamoaDB
    username: admin
    password: moamoathink33
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  redis:
#    host: localhost
#    port: 6379

logging.level:
  org.hibernate.SQL: debug
  com.amazonaws.util.EC2MetadataUtils: error
