spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: local
    include: oauth
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        #database: mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  redis:
#    host: localhost
#    port: 6379

logging.level:
  org.hibernate.SQL: debug

